image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  PROJECT_IMAGE: gitlab.example.com/techmohas/ecommerce-backend/cicd-setup:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: gitlab.example.com/techmohas/ecommerce-backend/cicd-setup:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.example.com/techmohas/ecommerce-backend/cicd-setup

build:
  stage: build
  script:
    - docker build --pull -t $PROJECT_IMAGE .
    - docker push $PROJECT_IMAGE

test:
  stage: test
  script:
    - docker pull $PROJECT_IMAGE
    - docker run $TEST_IMAGE npm test

release:
  stage: release
  script:
    - docker pull $PROJECT_IMAGE
    - docker tag $PROJECT_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - cicd-setup