image: docker:latest
services:
- name: docker:dind
stages:
- build
- release

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2376/

# before_script:
  # - ssh $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    # - docker build --pull -t https://$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME .
    # - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

release:
  stage: release
  tags:
    - deployment
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker compose up -d