stages:
  - publish
publish:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info
    - docker-compose --version
    - apk add --no-cache docker-compose
    

  script:
    - docker-compose down
    - docker-compose build
    - docker compose up -d 
    
