stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""


  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    
  only:
    - cicd-setup
deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment

  before_script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVERIP_MAIN >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG_LATEST"
    - ssh $SERVER_USER@$SERVER_IP "docker service update --image $TAG_LATEST --force $SERVICE_NAME"

  environment:
    name: production
    url: http://165.232.42.207
  only:
    - cicd-setup

# .gitlab-ci.yml
# publish:
#   image: docker:latest
#   stage: publish
#   tags:
#     - deployment
#   services:
#     - name: docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375/

#   before_script:
#     - docker info
#     - docker-compose --version
#   script:
#      - docker compose up -d 
    

