image: docker:latest
services:
- name: docker:dind
  alias: ecommerce-backend

stages:
- build
- release

variables:
  DOCKER_HOST: tcp://ecommerce-backend:2375/

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

release:
  stage: release
  tags:
    - deployment
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker compose up -d