image: docker:latest
services:
- name: docker:dind
  alias: thedockerhost

stages:
- build
# - test
# - release

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  PROJECT_IMAGE: gitlab.com/techmohas/ecommerce-backend/cicd-setup:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: gitlab.com/techmohas/ecommerce-backend/cicd-setup:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - echo $CI_COMMIT_REF_NAME

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# test:
#   stage: test
#   tags:
#     - deployment
#   script:
#     - docker pull $PROJECT_IMAGE
#     - docker run $CI_REGISTRY_IMAGE npm test

# release:
#   stage: release
#   tags:
#     - deployment
#   script:
#     - docker pull $PROJECT_IMAGE
#     - docker tag $PROJECT_IMAGE $RELEASE_IMAGE
#     - docker push $RELEASE_IMAGE
