image: docker:latest
services:
- name: docker:dind
  alias: thedockerhost

stages:
- build
- test
- release

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

test:
  stage: test
  tags:
    - deployment
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker run $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME npm test

release:
  stage: release
  tags:
    - deployment
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
    - docker compose up -d
