image: docker:latest
services:
- name: docker:dind
stages:
- build
- release
before_script:
  - apk add nmap
  - nmap -sT -p- docker

variables:

  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ''

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

release:
  stage: release
  tags:
    - deployment
  before_script:
      - apk update && apk add openssh-client
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_KEY")
      # - mkdir -p ~/.ssh
      # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

      - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVERIP_STAGING "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG"
    - ssh $SERVER_USER@$SERVER_IP "docker service update --force $SERVICE_NAME"
