image: docker:latest
services:
- name: docker:dind
  alias: thedockerhost

stages:
- build
- test
- release

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  PROJECT_IMAGE: gitlab.com/techmohas/ecommerce-backend/cicd-setup:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: gitlab.com/techmohas/ecommerce-backend/cicd-setup:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.com/techmohas/ecommerce-backend/cicd-setup

build:
  stage: build
  tags:
    - deployment
  script:
    - docker build --pull -t $PROJECT_IMAGE .
    - docker push $PROJECT_IMAGE

test:
  stage: test
  tags:
    - deployment
  script:
    - docker pull $PROJECT_IMAGE
    - docker run $TEST_IMAGE npm test

release:
  stage: release
  tags:
    - deployment
  script:
    - docker pull $PROJECT_IMAGE
    - docker tag $PROJECT_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
